language: erlang

env:
  - LUA=""

branches:
  only:
    - master

install:
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

script: "busted"
